- name: demo varaibles
  hosts: frontend
  connection: frontend
  vars: 
   course: "Ansible"
   trainer: "siva"
   duration: "100hrs"
  tasks:
  - debug:
     msg: "hi,i am learning {{course}}, trainer is {{siva}}, duration is {{duration}}"