- name: demo on vars_files
  hosts: local
  conection: local
  vars_files: 
  - course.yaml
  tasks:
  - name: print information
    debug:
     msg: "hi,i am learning {{COURSE}}, trainer is {{TRAINER}}, duration is {{DURATION}}"
       

  
