

[frontend]
172.31.37.132

[frontend:vars]
COURSE="Ansible"
TRAINER="sivakumar"
DURATION="10hrs"


[local]
localhosts

local group vars
[local:vars]
COURSE="Ansible"
TRAINER="sivakumar"
DURATION="10hrs"