

[frontend]
172.31.37.132 ;COURSE="Ansible for Node1" #host varaibles
172.31.32.125 ;COURSE="Ansible for Node2

Ansible1/group_vars/frontend.yaml
#[frontend:vars]
;COURSE="Ansible"
;RAINER="sivakumar"
;DURATION="10hrs"


; [local]
; localhosts

; local group vars
; [local:vars]
; COURSE="Ansible"
; TRAINER="sivakumar"
; DURATION="10hrs"